name: FMCRandomChoose
version: '${project.version}'
main: me.bunnykick.randomchoose.RandomChoose
api-version: 1.18
authors: [ BunnyKick ]
description: Choose a random Player for Stuff

commands:
  chooserandom:
    usage: /<command>
    aliases: [cr]
  randomreward:
    usage: /<command>
    aliases: [reward]